name = "MetaCompute"
testRunner = "MetaComputeTest"
defaultTargets = ["MetaCompute"]

[leanOptions]
pp.unicode.fun = true
pp.proofs.withType = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0-rc3"

[[lean_lib]]
name = "MetaCompute"

[[lean_lib]]
name = "MetaComputeTest"
